In [1]:
import pandas as pd

In [5]:
%pip install -U scikit-learn

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 23.0.1 -> 23.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [7]:
from sklearn.linear_model import LinearRegression

In [11]:
import seaborn as sns

In [13]:
from sklearn.datasets import load_boston

ImportError: 
`load_boston` has been removed from scikit-learn since version 1.2.

The Boston housing prices dataset has an ethical problem: as
investigated in [1], the authors of this dataset engineered a
non-invertible variable "B" assuming that racial self-segregation had a
positive impact on house prices [2]. Furthermore the goal of the
research that led to the creation of this dataset was to study the
impact of air quality but it did not give adequate demonstration of the
validity of this assumption.

The scikit-learn maintainers therefore strongly discourage the use of
this dataset unless the purpose of the code is to study and educate
about ethical issues in data science and machine learning.

In this special case, you can fetch the dataset from the original
source::

    import pandas as pd
    import numpy as np

    data_url = "http://lib.stat.cmu.edu/datasets/boston"
    raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
    data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
    target = raw_df.values[1::2, 2]

Alternative datasets include the California housing dataset and the
Ames housing dataset. You can load the datasets as follows::

    from sklearn.datasets import fetch_california_housing
    housing = fetch_california_housing()

for the California housing dataset and::

    from sklearn.datasets import fetch_openml
    housing = fetch_openml(name="house_prices", as_frame=True)

for the Ames housing dataset.

[1] M Carlisle.
"Racist data destruction?"
<https://medium.com/@docintangible/racist-data-destruction-113e3eff54a8>

[2] Harrison Jr, David, and Daniel L. Rubinfeld.
"Hedonic housing prices and the demand for clean air."
Journal of environmental economics and management 5.1 (1978): 81-102.
<https://www.researchgate.net/publication/4974606_Hedonic_housing_prices_and_the_demand_for_clean_air>


In [14]:
    import pandas as pd
    import numpy as np

    data_url = "http://lib.stat.cmu.edu/datasets/boston"
    raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
    data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
    target = raw_df.values[1::2, 2]

In [9]:
from sklearn.model_selection import train_test_split

In [15]:
raw_df

0      1      2    3      4      5     6       7    8      9   \
0       0.00632  18.00   2.31  0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1     396.90000   4.98  24.00  NaN    NaN    NaN   NaN     NaN  NaN    NaN   
2       0.02731   0.00   7.07  0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
3     396.90000   9.14  21.60  NaN    NaN    NaN   NaN     NaN  NaN    NaN   
4       0.02729   0.00   7.07  0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
...         ...    ...    ...  ...    ...    ...   ...     ...  ...    ...   
1007  396.90000   5.64  23.90  NaN    NaN    NaN   NaN     NaN  NaN    NaN   
1008    0.10959   0.00  11.93  0.0  0.573  6.794  89.3  2.3889  1.0  273.0   
1009  393.45000   6.48  22.00  NaN    NaN    NaN   NaN     NaN  NaN    NaN   
1010    0.04741   0.00  11.93  0.0  0.573  6.030  80.8  2.5050  1.0  273.0   
1011  396.90000   7.88  11.90  NaN    NaN    NaN   NaN     NaN  NaN    NaN   

        10  
0     15.3  
1      NaN  
2     17.8  
3      NaN  
4     17.8  
...    ...  
1007   NaN  
1008  21.0  
1009   NaN  
1010  21.0  
1011   NaN  

[1012 rows x 11 columns]

In [10]:
reg = LinearRegression()

In [16]:
data

array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 1.5300e+01, 3.9690e+02,
        4.9800e+00],
       [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9690e+02,
        9.1400e+00],
       [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9283e+02,
        4.0300e+00],
       ...,
       [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        5.6400e+00],
       [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9345e+02,
        6.4800e+00],
       [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        7.8800e+00]])

In [17]:
target

array([24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9, 15. ,
       18.9, 21.7, 20.4, 18.2, 19.9, 23.1, 17.5, 20.2, 18.2, 13.6, 19.6,
       15.2, 14.5, 15.6, 13.9, 16.6, 14.8, 18.4, 21. , 12.7, 14.5, 13.2,
       13.1, 13.5, 18.9, 20. , 21. , 24.7, 30.8, 34.9, 26.6, 25.3, 24.7,
       21.2, 19.3, 20. , 16.6, 14.4, 19.4, 19.7, 20.5, 25. , 23.4, 18.9,
       35.4, 24.7, 31.6, 23.3, 19.6, 18.7, 16. , 22.2, 25. , 33. , 23.5,
       19.4, 22. , 17.4, 20.9, 24.2, 21.7, 22.8, 23.4, 24.1, 21.4, 20. ,
       20.8, 21.2, 20.3, 28. , 23.9, 24.8, 22.9, 23.9, 26.6, 22.5, 22.2,
       23.6, 28.7, 22.6, 22. , 22.9, 25. , 20.6, 28.4, 21.4, 38.7, 43.8,
       33.2, 27.5, 26.5, 18.6, 19.3, 20.1, 19.5, 19.5, 20.4, 19.8, 19.4,
       21.7, 22.8, 18.8, 18.7, 18.5, 18.3, 21.2, 19.2, 20.4, 19.3, 22. ,
       20.3, 20.5, 17.3, 18.8, 21.4, 15.7, 16.2, 18. , 14.3, 19.2, 19.6,
       23. , 18.4, 15.6, 18.1, 17.4, 17.1, 13.3, 17.8, 14. , 14.4, 13.4,
       15.6, 11.8, 13.8, 15.6, 14.6, 17.8, 15.4, 21

In [18]:
x_df = pd.DataFrame(data)

In [19]:
y_df = pd.DataFrame(target)

In [20]:
x_df

0     1      2    3      4      5     6       7    8      9     10  \
0    0.00632  18.0   2.31  0.0  0.538  6.575  65.2  4.0900  1.0  296.0  15.3   
1    0.02731   0.0   7.07  0.0  0.469  6.421  78.9  4.9671  2.0  242.0  17.8   
2    0.02729   0.0   7.07  0.0  0.469  7.185  61.1  4.9671  2.0  242.0  17.8   
3    0.03237   0.0   2.18  0.0  0.458  6.998  45.8  6.0622  3.0  222.0  18.7   
4    0.06905   0.0   2.18  0.0  0.458  7.147  54.2  6.0622  3.0  222.0  18.7   
..       ...   ...    ...  ...    ...    ...   ...     ...  ...    ...   ...   
501  0.06263   0.0  11.93  0.0  0.573  6.593  69.1  2.4786  1.0  273.0  21.0   
502  0.04527   0.0  11.93  0.0  0.573  6.120  76.7  2.2875  1.0  273.0  21.0   
503  0.06076   0.0  11.93  0.0  0.573  6.976  91.0  2.1675  1.0  273.0  21.0   
504  0.10959   0.0  11.93  0.0  0.573  6.794  89.3  2.3889  1.0  273.0  21.0   
505  0.04741   0.0  11.93  0.0  0.573  6.030  80.8  2.5050  1.0  273.0  21.0   

         11    12  
0    396.90  4.98  
1    396.90  9.14  
2    392.83  4.03  
3    394.63  2.94  
4    396.90  5.33  
..      ...   ...  
501  391.99  9.67  
502  396.90  9.08  
503  396.90  5.64  
504  393.45  6.48  
505  396.90  7.88  

[506 rows x 13 columns]

In [21]:
y_df

0
0    24.0
1    21.6
2    34.7
3    33.4
4    36.2
..    ...
501  22.4
502  20.6
503  23.9
504  22.0
505  11.9

[506 rows x 1 columns]

In [23]:
print(x_df.shape)
print(y_df.shape)

(506, 13)
(506, 1)


In [24]:
(x_train,x_test,y_train,y_test)=train_test_split(x_df,y_df,test_size=0.33,random_state=7)

In [27]:
reg.fit(x_train,y_train)

LinearRegression()

In [28]:
reg.coef_

array([[-1.09873363e-01,  2.58433901e-02,  9.28160447e-03,
         2.59051078e+00, -1.56397981e+01,  5.35032613e+00,
        -1.40976088e-02, -1.30728719e+00,  2.69509709e-01,
        -1.12604281e-02, -9.68767369e-01,  1.00291422e-02,
        -3.86574789e-01]])

In [30]:
raw_df.columns

Int64Index([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10], dtype='int64')

In [31]:
raw_df.describe()

0            1            2           3           4   \
count  1012.000000  1012.000000  1012.000000  506.000000  506.000000   
mean    180.143778    12.008350    16.834792    0.069170    0.554695   
std     188.132839    17.250728     9.912616    0.253994    0.115878   
min       0.006320     0.000000     0.460000    0.000000    0.385000   
25%       0.257830     0.000000     8.375000    0.000000    0.449000   
50%      24.021000     7.240000    18.100000    0.000000    0.538000   
75%     391.435000    16.780000    21.890000    0.000000    0.624000   
max     396.900000   100.000000    50.000000    1.000000    0.871000   

               5           6           7           8           9           10  
count  506.000000  506.000000  506.000000  506.000000  506.000000  506.000000  
mean     6.284634   68.574901    3.795043    9.549407  408.237154   18.455534  
std      0.702617   28.148861    2.105710    8.707259  168.537116    2.164946  
min      3.561000    2.900000    1.129600    1.000000  187.000000   12.600000  
25%      5.885500   45.025000    2.100175    4.000000  279.000000   17.400000  
50%      6.208500   77.500000    3.207450    5.000000  330.000000   19.050000  
75%      6.623500   94.075000    5.188425   24.000000  666.000000   20.200000  
max      8.780000  100.000000   12.126500   24.000000  711.000000   22.000000

In [36]:
y_pred = reg.predict(x_test)

In [37]:
y_pred

array([[22.79452001],
       [19.13291418],
       [19.99522168],
       [19.10993674],
       [ 5.81780034],
       [12.03127097],
       [21.35169945],
       [28.7881867 ],
       [29.14059436],
       [14.04658365],
       [ 6.2195337 ],
       [32.88907823],
       [18.81942864],
       [19.97041679],
       [37.2925807 ],
       [22.74417409],
       [29.20001797],
       [33.3506124 ],
       [10.51851694],
       [24.57901202],
       [21.1898833 ],
       [27.65103464],
       [37.74811144],
       [13.54395091],
       [ 9.12733391],
       [15.28123066],
       [35.80751041],
       [26.04711935],
       [25.76285076],
       [27.24116638],
       [18.94396901],
       [30.63133182],
       [31.57249618],
       [16.55313165],
       [40.09549086],
       [20.28393071],
       [18.927392  ],
       [17.35560931],
       [21.7094217 ],
       [28.29900274],
       [27.16901375],
       [19.20081248],
       [14.14659823],
       [25.90401421],
       [18.40965462],
       [14

In [38]:
y_test

0
357  21.7
337  18.5
327  22.2
13   20.4
418   8.8
..    ...
81   23.9
487  20.6
314  23.8
187  32.0
425   8.3

[167 rows x 1 columns]

In [39]:
from sklearn.metrics import mean_squared_error

In [41]:
mean_squared_error(y_test,y_pred)

25.32230742358627

In [42]:
from sklearn.metrics import mean_squared_error

# True values
y_true = [3, 5, 2, 7]

# Predicted values
y_pred = [2.5, 4.8, 1.9, 6.5]

# Calculate mean squared error
mse = mean_squared_error(y_true, y_pred)

# Print the mean squared error
print("Mean Squared Error:", mse)

Mean Squared Error: 0.1375
